# Generated by Django 4.2.4 on 2023-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.TextField(verbose_name='Topics')),
                ('solutions_amount', models.IntegerField(verbose_name='Solutions amount')),
                ('problem_name', models.CharField(max_length=255, verbose_name='Problem name')),
                ('index', models.CharField(max_length=100, verbose_name='Index')),
                ('raiting', models.IntegerField(blank=True, null=True, verbose_name='Raiting')),
            ],
            options={
                'verbose_name': 'problem',
                'verbose_name_plural': 'problems',
            },
        ),
    ]
