# Generated by Django 4.2.4 on 2023-08-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solutions_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Solutions amount'),
        ),
    ]
