# Generated by Django 4.2.4 on 2023-08-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_problem_solutions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='raiting',
        ),
        migrations.AddField(
            model_name='problem',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='rating'),
        ),
    ]
