# Generated by Django 4.2.4 on 2023-08-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.AddField(
            model_name='problem',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Is_used'),
        ),
    ]
